### ISSUE TITLE
Issues on start

### ISSUE THREAD

**Issue by DonkeyXBT** [DracoR22/handi-cat_wallet-tracker#3]
src/lib/token-utils.ts:2:1 - error TS2578: Unused '@ts-expect-error' directive.

2 // @ts-expect-error
  ~~~~~~~~~~~~~~~~~~~

src/parsers/token-parser.ts:2:59 - error TS2305: Module '"@metaplex-foundation/mpl-token-metadata"' has no exported member 'deprecated'.

2 import { Collection, Data, Metadata, TokenStandard, Uses, deprecated } from '@metaplex-foundation/mpl-token-metadata'
                                                            ~~~~~~~~~~


Found 2 errors in 2 files.

Errors  Files
     1  src/lib/token-utils.ts:2
     1  src/parsers/token-parser.ts:2
 ELIFECYCLE  Command failed with exit code 2.

**Comment by DracoR22** [comment]
Try deleting node_modules folder and install dependencies again

**Comment by DonkeyXBT** [comment]
> Try deleting node_modules folder and install dependencies again

Does not work still, same issue

**Comment by DonkeyXBT** [comment]
src/lib/token-utils.ts:2:1 - error TS2578: Unused '@ts-expect-error' directive.

2 // @ts-expect-error
  ~~~~~~~~~~~~~~~~~~~

src/parsers/token-parser.ts:2:59 - error TS2305: Module '"@metaplex-foundation/mpl-token-metadata"' has no exported member 'deprecated'.

2 import { Collection, Data, Metadata, TokenStandard, Uses, deprecated } from '@metaplex-foundation/mpl-token-metadata'
                                                            ~~~~~~~~~~

src/parsers/token-parser.ts:25:32 - error TS2693: 'Metadata' only refers to a type, but is being used as a value here.

25     const tokenContent = await Metadata.fromAccountAddress(this.connection, tokenmetaPubkey)
                                  ~~~~~~~~

**Comment by DracoR22** [comment]
I think I found the solution, uninstall @metaplex-foundation/mpl-token-metadata .
So if you are using npm it would be: npm uninstall @metaplex-foundation/mpl-token-metadata, then just install it again: npm install @metaplex-foundation/mpl-token-metadata.

I think the problem might happen if you use another package manager instead of pnpm, let me know if this fixed the problem.

**Comment by WalterHackwell** [comment]
> I think I found the solution, uninstall @metaplex-foundation/mpl-token-metadata . So if you are using npm it would be: npm uninstall @metaplex-foundation/mpl-token-metadata, then just install it again: npm install @metaplex-foundation/mpl-token-metadata.
> 
> I think the problem might happen if you use another package manager instead of pnpm, let me know if this fixed the problem.

I have the same issue and it is not working

**Comment by kungl** [comment]
I've used simple `npm i` to install dependencies. Install [pnpm](https://pnpm.io/installation ) and install dependecies with `pnpm i`solved the issue.

**Comment by WalterHackwell** [comment]
> I've used simple `npm i` to install dependencies. Install [pnpm](https://pnpm.io/installation) and install dependecies with `pnpm i`solved the issue.

Thanks, I tried that but nothing. Sadly.

**Comment by DonkeyXBT** [comment]
Ok, I have tried another server and it works for me now. One thing that I still do not understand is the APP_URL, what do I have to set there?

**Comment by DracoR22** [comment]
> Ok, I have tried another server and it works for me now. One thing that I still do not understand is the APP_URL, what do I have to set there?

In APP_URL you set the url of your deployed server if you are using Telegram webhook
