### ISSUE TITLE
Jupiter swap alert does not work for all tokens

### ISSUE THREAD

**Issue by Tugduall** [DracoR22/handi-cat_wallet-tracker#4]
While testing the bot, I realized that not all swaps on Jupiter were taken into account.

I try to swap from SOL to Pnut (2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump) but I get no alert in Telegram. I use SOLANA_NETWORK.

Could this be because Jupiter has been upgraded to v6?

Would you have an idea of the problem please?

**Comment by L4r5s** [comment]
in src/lib/watch-transactions.ts in isRelevantTransaction() it should be: 
   if (logString.includes(PUMP_FUN_TOKEN_MINT_AUTH)) {
      return { isRelevant: true, swap: 'mint_pumpfun' }
    }
    if (logString.includes(PUMP_FUN_PROGRAM_ID)) {
      return { isRelevant: true, swap: 'pumpfun' }
    }
    if (logString.includes(JUPITER_PROGRAM_ID)) {
      return { isRelevant: true, swap: 'jupiter' }
    }
    if (logString.includes(RAYDIUM_PROGRAM_ID)) {
      return { isRelevant: true, swap: 'raydium' }
    }

Jupiter has to return before Raydium or its gonna count it as a Raydium transaction because they share program ids most of the times

**Comment by Tugduall** [comment]
Thank you, I will try this
